baseURL = "https://blog.nownabe.com/"
enableEmoji = true
googleAnalytics = "UA-37580164-4"
languageCode = "ja-JP"
rssUri = "feed.xml"
title = "nownab.log"
paginate = 20
pygmentsUseClasses = true
pygmentsCodefences = true


[outputs]
home = ["HTML", "RSS"]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss+xml"
baseName = "feed"

[params]
author = "nownabe"
description = "the nownabe's life log"

[related]
threshold = 80
includeNewer = true
toLower = true

[[related.indices]]
name = "tags"
weight = 100

[[related.indices]]
name = "date"
weight = 10
