name: Deploy Hugo
author: nownabe
description: Deploy Hugo site to GitHub Pages
inputs:
  branch:
    description: Branch for GitHub Pages
    required: false
    default: gh-pages
  deploy_key:
    description: Deploy key
    required: true
  template:
    description: Name of Hugo template
    required: true
runs:
  using: docker
  image: Dockerfile
