name: deploy
on:
  push:
    branches:
      - source
    tags:
      - '!*'

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: deploy
        uses: ./.github/actions/deploy
        with:
          branch: master
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          template: nownablog
